[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">= 3.8"
dependencies = ["django>=3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
