[project]
name = "random-wikipedia-article"
version = "0.1"
dependencies = ["pytest"]

[project.entry-points.pytest11]
random-wikipedia-article = "random_wikipedia_article"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

