[project]
name = "random-wikipedia-article"
dynamic = ["version"]

[project.scripts]
random-wikipedia-article = "random_wikipedia_article:main"

[tool.hatch.version]
path = "src/random_wikipedia_article/__init__.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

